# Generated by Django 6.0 on 2025-12-19 11:35

import cloudinary.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Base', '0002_delete_produit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_fr', models.CharField(max_length=255, verbose_name='Nom (FR)')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name (EN)')),
                ('is_active', models.BooleanField(default=True)),
                ('cover_image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Cover Image')),
                ('website_url', models.URLField(blank=True, help_text="Partner's official website link", null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'ordering': ['-created_at'],
            },
        ),
    ]
