# Generated by Django 6.0 on 2025-12-20 23:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('visit', 'Visit'), ('click', 'Click'), ('contact_submit', 'Contact submit'), ('mail_sent', 'Mail sent'), ('video_play', 'Video play'), ('image_download', 'Image download'), ('form_error', 'Form error'), ('auth_login', 'Auth login'), ('admin_action', 'Admin action')], max_length=50)),
                ('page', models.CharField(blank=True, max_length=255, null=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=50, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=512, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action_type'], name='Base_activi_action__24ca63_idx'), models.Index(fields=['created_at'], name='Base_activi_created_57ac7e_idx'), models.Index(fields=['page'], name='Base_activi_page_875dd3_idx')],
            },
        ),
    ]
