# Generated by Django 4.2.27 on 2025-12-23 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0008_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('cover_photo', models.URLField()),
                ('image_1', models.URLField(blank=True, null=True)),
                ('image_2', models.URLField(blank=True, null=True)),
                ('image_3', models.URLField(blank=True, null=True)),
                ('image_4', models.URLField(blank=True, null=True)),
                ('image_5', models.URLField(blank=True, null=True)),
                ('image_6', models.URLField(blank=True, null=True)),
                ('image_7', models.URLField(blank=True, null=True)),
                ('image_8', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
