# Generated by Django 4.2.27 on 2025-12-23 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0009_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeurmission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valeurmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='valeur_mission/'),
        ),
    ]
