# Generated by Django 4.2.27 on 2025-12-23 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0010_valeurmission_description_valeurmission_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurmission',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
