# Generated by Django 4.2.27 on 2025-12-23 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0011_alter_valeurmission_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valeurmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Valeur & Mission', 'verbose_name_plural': 'Valeurs & Missions'},
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='valeur_mission/'),
        ),
    ]
