# Generated by Django 4.2.27 on 2025-12-23 23:50

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0012_alter_valeurmission_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valeurmission',
            options={'ordering': ['-created_at'], 'verbose_name': 'Valeur / Mission', 'verbose_name_plural': 'Valeurs / Missions'},
        ),
        migrations.AddField(
            model_name='valeurmission',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Photo'),
        ),
        migrations.AddField(
            model_name='valeurmission',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='mission',
            field=models.TextField(verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='titre',
            field=models.CharField(max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='valeur',
            field=models.TextField(verbose_name='Valeur'),
        ),
    ]
