# Generated by Django 4.2.27 on 2025-12-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0013_alter_valeurmission_options_valeurmission_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valeurmission',
            options={},
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='titre',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='valeur',
            field=models.TextField(),
        ),
    ]
