# Generated by Django 4.2.27 on 2025-12-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0015_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='description',
            field=models.TextField(default='Description manquante', verbose_name='Description (FR)'),
            preserve_default=False,
        ),
    ]
