# Generated by Django 4.2.27 on 2025-12-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0016_alter_home_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valeurmission',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='valeurmission',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='valeurmission',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='description',
            field=models.TextField(default='Description à compléte'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='mission',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='valeur',
            field=models.CharField(max_length=255),
        ),
    ]
