# Generated by Django 4.2.27 on 2025-12-25 12:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0017_remove_valeurmission_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valeurmission',
            name='image',
        ),
        migrations.AddField(
            model_name='valeurmission',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='valeurmission',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Photo'),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='mission',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='valeur',
            field=models.TextField(),
        ),
    ]
