# Generated by Django 4.2.27 on 2025-12-25 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0018_remove_valeurmission_image_valeurmission_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valeurmission',
            name='photo_url',
        ),
    ]
