# Generated by Django 4.2.27 on 2025-12-25 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0019_remove_valeurmission_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='valeurmission',
            name='photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL Photo'),
        ),
    ]
