# Generated by Django 4.2.27 on 2026-01-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0020_valeurmission_photo_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valeurmission',
            name='photo_url',
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='description',
            field=models.TextField(default='Description non définie'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='mission',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='photo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valeurmission',
            name='valeur',
            field=models.CharField(max_length=255),
        ),
    ]
