# Generated by Django 4.2.27 on 2026-01-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0021_remove_valeurmission_photo_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valeurmission',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='missions/'),
        ),
    ]
