# Generated by Django 4.2.27 on 2026-01-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0024_contactmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('general', 'Question générale'), ('support', 'Support technique'), ('partenariat', 'Partenariat'), ('commentaire', 'Commentaires et suggestions')], default='general', max_length=50),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
