# Generated by Django 4.2.27 on 2026-01-16 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0025_delete_contactmessage_alter_contact_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('question', 'Questions générales'), ('support', 'Support technique'), ('partenariat', 'Partenariat'), ('commentaire', 'Commentaires et suggestions')], default='question', max_length=50),
        ),
    ]
